[package]
name = "tgradish"
description = "Converts videos into Telegram video stickers, with the ability to bypass the 3 second limit"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "tgradish"
path = "src/main.rs"

[features]
# ffmpeg linked into the binary instead of separate executables
linked = ["tgradish-core/linked"]
linked-static = ["tgradish-core/linked-static"]

[dependencies]
tgradish-core.workspace = true

anyhow.workspace = true
arboard.workspace = true
clap.workspace = true
console.workspace = true
ctrlc.workspace = true
indicatif.workspace = true
png.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
tempfile.workspace = true
thiserror.workspace = true
toml.workspace = true

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
